### ISSUE TITLE
command_line: implement sspm-install command

### ISSUE THREAD

**Issue by sh19910711** [social-snippet/social-snippet#57]
### summary

``` bash
$ sspm install [options] <repo-name>
```
### TODO
- [x] to resolve dependencies
- [ ] to check already installed repository
- [ ] to check update repository
